# This file is automatically generated from targets.yml.whisker:
# Follow the manual to check and run the pipeline:
# https://books.ropensci.org/targets/walkthrough.html#inspect-the-pipeline # nolint

# Load packages required to define the pipeline:
library(targets)
library(tarchetypes)
library(rlang)

library(crew)
tar_option_set(
  controller = crew_controller_local(workers = 10)
)

#library(dplyr)
#options(clustermq.scheduler = "multicore")

tar_config_set(
  reporter_make = "summary"
  )

# Set target options:
tar_option_set(
  packages = c("traits.build"), # packages that your targets need to run
  format = "rds" # default storage format
  # Set other options as needed.
)
valid_datasets <- function(dataset_ids = dir("data")) {
  
  i <- purrr::map_lgl(dataset_ids, ~all(file.exists(sprintf("%s/%s/%s", "data", .x, c("data.csv", "metadata.yml")))))
  dataset_ids[i]
}

dataset_ids <- valid_datasets()

metadata_file <- function(x) {
  sprintf("data/%s/metadata.yml", x)
}
list(
  tar_target(file_DESCRIPTION, "config/metadata.yml", format = "file"),
  tar_target(version_number, util_get_version(file_DESCRIPTION)),
  tar_target(git_SHA, util_get_SHA()),
  tar_target(file_traits, "config/traits.yml", format = "file"),
  tar_target(definitions, get_schema(file_traits, "traits")),
  tar_target(file_unit_conversions, "config/unit_conversions.csv", format = "file"),
  tar_target(unit_conversions, get_unit_conversions(file_unit_conversions)),
  tar_target(schema, get_schema()),
  tar_target(file_taxon, "config/taxon_list.csv", format = "file"),
  tar_target(taxon_list, read_csv_char(file_taxon)),
  tar_target(file_resource_metadata, "config/metadata.yml", format = "file"),
  tar_target(resource_metadata, get_schema(file_resource_metadata, "metadata")),
  
  # file targets
  tar_map(
    list(id = dataset_ids),
    tar_target(file_metadata, sprintf("data/%s/metadata.yml", id)),
    tar_target(file_data, sprintf("data/%s/data.csv", id)),
    # configure
    tar_target(config, dataset_configure(file_metadata, definitions, unit_conversions))
  ),
  tar_map(
    list(conf = config, fdata = file_data),
        # process
    tar_target(raw, dataset_process(fdata, conf, schema, resource_metadata))
  )
)
