# This file is automatically generated from targets.yml.whisker:
# Follow the manual to check and run the pipeline:
# https://books.ropensci.org/targets/walkthrough.html#inspect-the-pipeline # nolint

# Load packages required to define the pipeline:
library(targets)
library(tarchetypes)
library(rlang)

#library(dplyr)
options(clustermq.scheduler = "multicore")

tar_config_set(
  reporter_make = "summary"
  )

# Set target options:
tar_option_set(
  packages = c("austraits.build"), # packages that your targets need to run
  format = "rds" # default storage format
  # Set other options as needed.
)
valid_datasets <- function(dataset_ids = dir("data")) {
  
  i <- purrr::map_lgl(dataset_ids, ~all(file.exists(sprintf("%s/%s/%s", "data", .x, c("data.csv", "metadata.yml")))))
  dataset_ids[i]
}

dataset_ids <- valid_datasets()[1:5]

file_metadata_symbol <- rlang::syms(sprintf("file_metadata_%s", dataset_ids))
file_data_symbol <- rlang::syms(sprintf("file_data_%s", dataset_ids))
config_symbol <- rlang::syms(sprintf("config_%s", dataset_ids))
data_symbol <- rlang::syms(dataset_ids)

list(
  tar_target(file_DESCRIPTION, "DESCRIPTION", format = "file"),
  tar_target(version_number, desc_get_version(file_DESCRIPTION)),
  tar_target(git_SHA, get_SHA()),
  tar_target(file_traits, "config/traits.yml", format = "file"),
  tar_target(definitions, load_schema(file_traits, "traits")),
  tar_target(file_unit_conversions, "config/unit_conversions.csv", format = "file"),
  tar_target(unit_conversions, make_unit_conversion_functions(file_unit_conversions)),
  tar_target(schema, load_schema()),
  tar_target(file_taxon, "config/taxon_list.csv", format = "file"),
  tar_target(taxon_list, read_csv_char(file_taxon)),
  
  tar_eval(
    tar_target(symbol, filename, format = "file"),
    values = list(symbol = file_metadata_symbol, filename = sprintf("data/%s/metadata.yml", dataset_ids))
  ),

  tar_eval(
    tar_target(symbol, filename, format = "file"),
    values = list(symbol = file_data_symbol, filename = sprintf("data/%s/data.csv", dataset_ids))
  ), 

  tar_eval(
    tar_target(symbol, subset_config(filename,  definitions,  unit_conversions)),
    values = list(symbol = config_symbol, filename = file_metadata_symbol)
  ), 

  tar_eval(
    tar_target(symbol, load_dataset(filename, config, schema)),
    values = list(symbol = data_symbol, filename = file_data_symbol, config = config_symbol)
  )
)
